import { describe, it, expect } from 'vitest';
import {
  calculate,
  prec,
  floor,
  type DosingInputs,
  type DosingResult,
} from './dosing';

/**
 * Parity suite for the TB Dosage Calculator.
 *
 * Each `DosingResult` below was computed BY HAND from the CFF equations (not
 * generated by the module under test) so the suite is an independent oracle.
 * VECTOR 1 is the worked example from the live-page screenshot and is the
 * authoritative parity anchor (Male, 100 kg, 185 cm, age 35, Cr 1.0).
 */

interface Vector {
  name: string;
  input: DosingInputs;
  expect: DosingResult;
}

const vectors: Vector[] = [
  {
    name: 'V1 — screenshot example: Male 100kg/185cm, age 35, Cr 1.0, no RRT (normal renal)',
    input: { gender: '1', weight: 100, height: 185, age: 35, creatinine: 1, rrt: '' },
    expect: {
      bmi: '29.2',
      leanBodyWeight: '72.6',
      crcl: '145.8',
      renalCorrection: 'Follow dose frequency as instructed below',
      pyrazinamideRange: '1500 - 2000mg(max dose)',
      pyrazinamidePrescription: '1500mg(20.7mg/kg) per day',
      ethambutolRange: '1200 - 1600mg(max dose)',
      ethambutolPrescription: '1200mg(16.5mg/kg) per day',
    },
  },
  {
    name: 'V2 — empty form: everything pending/blank',
    input: { gender: '', weight: '', height: '', age: '', creatinine: '', rrt: '' },
    expect: {
      bmi: '',
      leanBodyWeight: 'Pending input data',
      crcl: '',
      renalCorrection: 'Follow dose frequency as instructed below',
      pyrazinamideRange: 'Pending input data',
      pyrazinamidePrescription: 'Pending input data',
      ethambutolRange: 'Pending input data',
      ethambutolPrescription: 'Pending input data',
    },
  },
  {
    name: 'V3 — Female 45kg/160cm, age 40, Cr 0.8, RRT=No (normal renal, low LBW <40)',
    input: { gender: '2', weight: 45, height: 160, age: 40, creatinine: 0.8, rrt: 'No' },
    expect: {
      bmi: '17.6',
      leanBodyWeight: '36.4',
      crcl: '66.4',
      renalCorrection: 'Follow dose frequency as instructed below',
      pyrazinamideRange: '750 - 1000mg per day',
      pyrazinamidePrescription: '750mg(20.6mg/kg) per day',
      ethambutolRange: '600 - 800mg per day',
      ethambutolPrescription: '600mg(16.5mg/kg) per day',
    },
  },
  {
    name: 'V4 — Male 70kg/175cm, age 50, Cr 1.2, RRT=Yes (dialysis path despite high CrCl)',
    input: { gender: '1', weight: 70, height: 175, age: 50, creatinine: 1.2, rrt: 'Yes' },
    expect: {
      bmi: '22.9',
      leanBodyWeight: '56.5',
      crcl: '72.9',
      renalCorrection:
        'Dosing is the same mg per dose, but given less frequently according to method of renal replacement. If on intermittent hemodialysis, doses are timed after each HD session. For other forms of renal replacement (e.g. peritoneal dialysis), the doses are timed 3 times a week',
      pyrazinamideRange: '1500 - 2000mg(max dose) with frequency based on renal replacement',
      pyrazinamidePrescription: '1750mg(31.0mg/kg) with frequency based on renal replacement',
      ethambutolRange: '1000 - 1600mg(max dose) with frequency based on renal replacement',
      ethambutolPrescription: '1000mg(17.7mg/kg) with frequency based on renal replacement',
    },
  },
  {
    name: 'V5 — Male 140kg/175cm, age 45, Cr 1.0, RRT=No (high BMI -> LBW fixed at max, normal renal)',
    input: { gender: '1', weight: 140, height: 175, age: 45, creatinine: 1, rrt: 'No' },
    expect: {
      bmi: '45.7 - recommend therapeutic drug monitoring. LBW fixed with male BMI > 43',
      leanBodyWeight: '72.4 - James equation unreliable at high BMIs. Fixed at max LBW.',
      crcl: '184.7',
      renalCorrection: 'Follow dose frequency as instructed below',
      pyrazinamideRange: '1500 - 2000mg(max dose)',
      pyrazinamidePrescription: '1500mg(20.7mg/kg) per day',
      ethambutolRange: '1200 - 1600mg(max dose)',
      ethambutolPrescription: '1200mg(16.6mg/kg) per day',
    },
  },
  {
    name: 'V6 — Male 200kg/185cm, age 40, Cr 1.0, RRT=Yes (max LBW + dialysis -> "range omitted" cap)',
    input: { gender: '1', weight: 200, height: 185, age: 40, creatinine: 1, rrt: 'Yes' },
    expect: {
      bmi: '58.4 - recommend therapeutic drug monitoring. LBW fixed with male BMI > 43',
      leanBodyWeight: '80.9 - James equation unreliable at high BMIs. Fixed at max LBW.',
      crcl: '277.8',
      renalCorrection:
        'Dosing is the same mg per dose, but given less frequently according to method of renal replacement. If on intermittent hemodialysis, doses are timed after each HD session. For other forms of renal replacement (e.g. peritoneal dialysis), the doses are timed 3 times a week',
      pyrazinamideRange: '2000mg(max dose) **minimum dosage at max, range omitted',
      pyrazinamidePrescription:
        '2000mg(max dose)** optimal doses for obese patients not established, consider therapeutic drug monitoring',
      ethambutolRange: '1400 - 1600mg(max dose) with frequency based on renal replacement',
      ethambutolPrescription: '1400mg(17.3mg/kg) with frequency based on renal replacement',
    },
  },
];

describe('TB dosing — full-form parity vectors', () => {
  for (const v of vectors) {
    it(v.name, () => {
      expect(calculate(v.input)).toEqual(v.expect);
    });
  }
});

describe('CFF helper semantics (per CFF docs)', () => {
  it('prec keeps fixed decimals and rounds half up', () => {
    expect(prec(10.33323, 2)).toBe('10.33');
    expect(prec(10.3365, 2)).toBe('10.34');
    expect(prec(10, 2)).toBe('10.00');
  });
  it('prec optional 3rd arg drops decimals when integer', () => {
    expect(prec(3, 2, true)).toBe('3');
    expect(prec(3, 2)).toBe('3.00');
  });
  it('floor rounds down, with optional multiple', () => {
    expect(floor(1.6)).toBe(1);
    expect(floor(2.6, 0.5)).toBe(2.5);
  });
});

describe('gating edge cases', () => {
  it('RRT=Yes forces the renal path even when CrCl is high', () => {
    const r = calculate({ gender: '1', weight: 70, height: 175, age: 50, creatinine: 1.2, rrt: 'Yes' });
    expect(r.pyrazinamidePrescription).toContain('with frequency based on renal replacement');
  });
  it('gender selected but no weight/height -> dosing stays pending', () => {
    const r = calculate({ gender: '1', weight: '', height: '', age: '', creatinine: '', rrt: '' });
    expect(r.leanBodyWeight).toBe('Pending input data');
    expect(r.pyrazinamideRange).toBe('Pending input data');
  });
});
